# Generated by Django 3.2.10 on 2021-12-13 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('url', models.URLField(max_length=512, verbose_name='URL do produto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(blank=True, max_length=1000, null=True)),
                ('preco', models.CharField(blank=True, max_length=10, null=True)),
                ('imagem', models.URLField(blank=True, max_length=512, null=True)),
                ('consultas', models.JSONField(blank=True, null=True)),
                ('ultima_consulta', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
